services:
  timescaledb:
    image: postgres:16
    container_name: postgres-fitstore
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: thales
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: fitstore
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local

