version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-s3-dev

    environment:
      SERVICES: s3
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

      LOCALSTACK_PERSISTENCE: '1'
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
    restart: unless-stopped
volumes:
  localstack_data: